language: rust
rust:
  - stable
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
branches:
    only:
    - master
before_install:
    - rustup target add wasm32-unknown-unknown
script:
  - cargo build --verbose --workspace
  - cargo test --verbose --workspace
