# My server runs linux. For compatability, check
# https://rust-lang.github.io/rustup-components-history/x86_64-unknown-linux-gnu.html
[toolchain]
channel = "nightly"
targets = [ "wasm32-unknown-unknown" ]
