name: artifact_upload

on:
  workflow_run:
    workflows: ["build"]
    types:
      - completed

jobs:
  upload:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: dist-latest
          path: dist/
