name: docker_push

on:
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  docker_push:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      # Install cargo deps
      - name: Installing Cargo dependencies
        run: |
          rustup update $TOOLCHAIN
          rustup default $TOOLCHAIN
          cargo install trunk

      # Trunk Build
      - name: Build cache
        run: |
          cargo build --target wasm32-unknown-unknown --verbose
          trunk build

      # Docker build
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            simbleau/website
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
